# Generated by Django 6.0.5 on 2026-07-16 20:41

import django.db.models.deletion
from django.db import migrations, models


def seed_homepage_settings_and_cards(apps, schema_editor):
    HomePageContactSection = apps.get_model('news', 'HomePageContactSection')
    HomepageSettings = apps.get_model('news', 'HomepageSettings')
    HomepageFeatureCard = apps.get_model('news', 'HomepageFeatureCard')

    contact_section = HomePageContactSection.objects.first()
    settings = HomepageSettings.objects.first()
    if settings is None:
        settings = HomepageSettings.objects.create(contact_section=contact_section)
    elif settings.contact_section_id is None and contact_section is not None:
        settings.contact_section = contact_section
        settings.save(update_fields=['contact_section'])

    default_cards = [
        {
            'slug': 'qualified-teachers',
            'title': 'Qualified Teachers',
            'description': 'Experienced educators committed to strong academic foundations and student growth.',
            'order': 1,
        },
        {
            'slug': 'modern-facilities',
            'title': 'Modern Facilities',
            'description': 'Purpose-built spaces that support active learning, collaboration, and creativity.',
            'order': 2,
        },
        {
            'slug': 'safe-environment',
            'title': 'Safe & Secure Environment',
            'description': 'A caring school community focused on wellbeing, safety, and confidence.',
            'order': 3,
        },
    ]

    for card in default_cards:
        HomepageFeatureCard.objects.get_or_create(
            settings=settings,
            slug=card['slug'],
            defaults={
                'title': card['title'],
                'description': card['description'],
                'order': card['order'],
                'is_active': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_homepagecontactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Inquiry',
                'verbose_name_plural': 'Homepage Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Aspire Academy', max_length=200)),
                ('hero_description', models.TextField(default='We provide a nurturing environment where learners grow academically, socially and personally.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/settings/')),
                ('footer_text', models.TextField(default='Premium learning, modern care, and a connected school community.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_section', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_settings', to='news.homepagecontactsection')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.CreateModel(
            name='HomepageFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/features/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='news.homepagesettings')),
            ],
            options={
                'verbose_name': 'Homepage Feature Card',
                'verbose_name_plural': 'Homepage Feature Cards',
                'ordering': ['order', 'id'],
                'unique_together': {('settings', 'slug')},
            },
        ),
        migrations.RunPython(seed_homepage_settings_and_cards, noop_reverse),
    ]
