# Generated by Django 6.0.5 on 2026-07-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_homepageinquiry_homepagesettings_homepagefeaturecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
