# Generated by Django 6.0.5 on 2026-06-23 21:50

import apps.finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=apps.finance.models.current_year),
        ),
    ]
