# Generated by Django 6.0.5 on 2026-06-23 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_budget_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budget_per_period',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('month__isnull', True), ('period_type', 'annual')), fields=('category', 'year'), name='unique_annual_budget_per_category_year'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('period_type', 'monthly')), fields=('category', 'period_type', 'year', 'month'), name='unique_monthly_budget_per_category_period'),
        ),
    ]
