# Generated by Django 6.0.5 on 2026-06-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3')], max_length=10)),
                ('year', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('school_tuition', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tuition_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-year', 'term'],
                'unique_together': {('student', 'term', 'year')},
            },
        ),
    ]
