# Generated by Django 6.0.5 on 2026-06-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_financial_synchronization'),
        ('students', '0005_payment_attendance_exams_auditlog'),
    ]

    operations = [
    ]
