# Generated by Django 6.0.5 on 2026-05-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cambridge_letter_grade', models.CharField(max_length=4)),
                ('term', models.CharField(max_length=32)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile')),
            ],
        ),
    ]
