# Generated by Django 6.0.5 on 2026-05-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='cambridge_letter_grade',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
