# Generated by Django 6.0.5 on 2026-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/'),
        ),
    ]
