# Generated by Django 6.0.5 on 2026-05-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacherprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
