# Generated by Django 6.0.5 on 2026-06-23 12:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_merge_20260623_1441'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('score', 'Score (0-100)'), ('rating', 'Rating (1-5)'), ('boolean', 'Yes/No'), ('choice', 'Multiple Choice')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text='For choice fields: ["Option 1", "Option 2"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Report Field',
                'verbose_name_plural': 'Report Fields',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('term', models.CharField(blank=True, choices=[('term1', 'Term 1'), ('term2', 'Term 2'), ('term3', 'Term 3')], max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('submission_opens', models.DateTimeField()),
                ('submission_deadline', models.DateTimeField()),
                ('approval_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_periods_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporting Period',
                'verbose_name_plural': 'Reporting Periods',
                'ordering': ['-year', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('reports_created', models.PositiveIntegerField(default=0)),
                ('reports_submitted', models.PositiveIntegerField(default=0)),
                ('reports_approved', models.PositiveIntegerField(default=0)),
                ('reports_published', models.PositiveIntegerField(default=0)),
                ('reports_pending', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='reports.reportingperiod')),
            ],
            options={
                'verbose_name': 'Reporting Analytics',
                'verbose_name_plural': 'Reporting Analytics',
            },
        ),
        migrations.CreateModel(
            name='BiWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict, help_text='Field name -> value pairs')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biweekly_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bi_weekly_reports', to='students.studentprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biweekly_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biweekly_reports_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biweekly_reports_updated', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reportingperiod')),
            ],
            options={
                'verbose_name': 'Bi-Weekly Report',
                'verbose_name_plural': 'Bi-Weekly Reports',
                'ordering': ['-period__start_date'],
                'unique_together': {('period', 'student')},
            },
        ),
    ]
