# Generated by Django 6.0.5 on 2026-07-15 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingperiod',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_periods_edited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='reporting_type',
            field=models.CharField(choices=[('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('mid_term', 'Mid-Term'), ('end_term', 'End-of-Term'), ('custom', 'Custom')], default='bi_weekly', max_length=20),
        ),
    ]
